version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /etc/localtime:/etc/localtime
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
     
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /etc/localtime:/etc/localtime
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /etc/localtime:/etc/localtime
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
      
  skywalking-oap:
    image: apache/skywalking-oap-server:7.0.0-es7
    container_name: skywalking-oap
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    environment:
      - SW_SW_STORAGE_ES_SSL_JKS_PATH=""
      - SW_STORAGE=elasticsearch7
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_ES_USER=elastic
      - SW_ES_PASSWORD=changeme
      - "TZ=Asia/Shanghai"

  skywalking-ui:
    image: apache/skywalking-ui:7.0.0
    container_name: skywalking-ui
    networks:
      - elk
    depends_on:
      - skywalking-oap
    links:
      - skywalking-oap        
    restart: always
    ports:
      - 9080:8080
    environment:
      - "collector.ribbon.listOfServers=skywalking-oap:12800"
      - "security.user.admin.password=admin"
      - "TZ=Asia/Shanghai"


networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
